### ISSUE TITLE
Doesn't work on miniconda env

### ISSUE THREAD

**Issue by jxng** [MultitudeVR/ChatCompletionsGUI#1]
Despite installing all the requirement, I'm getting this message while trying to prompt it
<img width="774" alt="Screen Shot 2023-04-26 at 12 03 00 pm" src="https://user-images.githubusercontent.com/67343929/234447104-6a1d8602-63eb-457c-8c4a-d185aa0dc046.png">
Was searching around for potential solutions so far, but this is the closest I found - https://community.openai.com/t/attributeerror-module-openai-has-no-attribute-chatcompletion/81490

Seem to be a potential env issue.

<img width="506" alt="Screen Shot 2023-04-26 at 12 02 37 pm" src="https://user-images.githubusercontent.com/67343929/234447044-c7266c69-14e9-48a7-abea-66700cbb9160.png">
Save Chat doesn't work on my end too

**Comment by Vwing** [comment]
I have seen this happen before. It was because I had an old installation of OpenAI's library in the cache, and even trying to update it to the latest version failed repeatedly because it would always reference that old version. The solution is to first try an update, and if that doesn't work then clear your cache. See: https://github.com/openai/openai-python/issues/253
